# Generated by Django 5.2.1 on 2025-06-13 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id_mantenimientov', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_mantenimiento', models.DateField()),
                ('tipo_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='Taller.tipomantenimiento')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='Taller.vehiculo')),
            ],
        ),
    ]
