# Generated by Django 5.2.1 on 2025-06-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taller', '0002_mantenimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='Repuestos',
            field=models.ManyToManyField(blank=True, related_name='mantenimientos', to='Taller.repuesto'),
        ),
    ]
