# Generated by Django 5.2.1 on 2025-06-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taller', '0003_mantenimiento_repuestos'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='precioTotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
